export { default as Password } from '@iconify-icons/ri/lock-password-line'
export { default as AddFill } from '@iconify-icons/ri/add-circle-line'
export { default as Upload } from '@iconify-icons/ri/upload-line'
export { default as Role } from '@iconify-icons/ri/admin-line'
export { default as More2Fill } from '@iconify-icons/ri/more-2-fill'
export { default as Reset } from '@iconify-icons/ri/restart-line'
export { default as Dept } from '@iconify-icons/ri/git-branch-line'

export { default as EditPen } from '@iconify-icons/ep/edit-pen'
export { default as Refresh } from '@iconify-icons/ep/refresh'
export { default as Delete } from '@iconify-icons/ep/delete'
export { default as More } from '@iconify-icons/ep/more-filled'
export { default as LocationCompany } from '@iconify-icons/ep/add-location'
export { default as OfficeBuilding } from '@iconify-icons/ep/office-building'
